---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /helm/shim
    schedule:
      interval: weekly
    groups:
      kubernetes:
        patterns:
          - k8s.io/apimachinery
          - k8s.io/client-go
    labels:
      - dependencies
  - package-ecosystem: gomod
    directory: /source/shim
    schedule:
      interval: weekly
    labels:
      - dependencies
