---
name: Vet changes
"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  vet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.21.3'
      - name: go vet
        run: |
          set -e
          go -C helm/shim vet ./...
          go -C helm/source vet ./...
